# fly.toml app configuration file generated for mitodoke on 2025-06-01T16:41:16+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mitodoke'
primary_region = 'nrt'

[build]
  dockerfile = './Dockerfile'

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

[processes]
web = "bin/rails server -b 0.0.0.0 -p 3000"

[[vm]]
  size = 'shared-cpu-1x'

[deploy]
release_command = "./bin/rails db:migrate"
